insert into barang(nama_brg, jenis_brg, jumlah_brg, berat_brg, deskripsi_brg, gambar_brg , toko_brg) values
('kaos9', 't-shirt', 20, 500, 'ini adalah contoh kaos mantap', 'a17.jpg', 'jualan baju'),
('kaos11', 't-shirt', 20, 500, 'ini adalah contoh kaos mantap', 'a1.png', 'jualan baju'),
('Kaos mantap', 't-shirt', 20, 500, 'ini adalah contoh kaos mantap', 'a9', 'jualan baju'),
('kaos2', 't-shirt', 20, 500, 'asdasdasdasd', 'a10', 'jualan baju'),
('kaos3', 't-shirt', 20, 500, 'asdasdasdasd', 'a11', 'jualan baju'),
('kaos4', 't-shirt', 20, 500, 'asdasdasdasd', 'a12', 'jualan baju'),
('kaos5', 't-shirt', 20, 500, 'asdasdasdasd', 'a13', 'jualan baju'),
('kaos6', 't-shirt', 20, 500, 'asdasdasdasd', 'a14', 'jualan baju'),
('kaos7', 't-shirt', 20, 500, 'asdasdasdasd', 'a15', 'jualan baju'),
('kaos8', 't-shirt', 20, 500, 'asdasdasdasd', 'a16', 'jualan baju'),
